version: '3.8'
services:
  jenkins:
    build: .
    ports:
      - "8081:8080" # Changed port number
      - "50001:50000"
    volumes:
      - jenkins-data:/var/jenkins_home # Changed volume name
volumes:
  jenkins-data: